### ISSUE TITLE
Possibly redundant work

### ISSUE THREAD

**Issue by MartinSStewart** [nicmr/compgeo#1]
Hi, this looks like a cool package but I noticed that some of the features already exist in the [elm-geometry](https://package.elm-lang.org/packages/ianmackenzie/elm-geometry/latest/) package. I guess this might not be an issue since in the readme you mention that this will be part of a lecture but otherwise I figured I'd let you know so you don't need to do extra work.

**Comment by nicmr** [comment]
Hi Martin,
thanks for the heads-up! 👍 
I'm aware of elm-geometry and know this package will probably never get anywhere near its scope or quality.
It's really primarily a practical exercise for the algorithms lecture I'm attending this semester.
I've also never published an Elm package before and wanted to go through that process as a learning experience.

I see how it could be problematic if somebody new to Elm encounters my package and ends up thinking this is the best the elm ecosystem has to offer regarding geometry.
I think it's for the best if I add add some highly visible warnings about this package's immaturity and a suggestion to use elm-geometry to the top of package docs.

If you have any additional suggestions, please let me know!

**Comment by ianmackenzie** [comment]
Hi @nicmr I was also curious when I saw the package crop up =) Great to see others working in this space!

How do you plan on licensing this code once it's done? It would be great at some point to compare your implementations of convex hull, polygon triangulation etc. to the existing ones in `elm-geometry`; if it turns out your implementations are faster and/or more accurate, would you be open to me merging those into `elm-geometry` somehow? Might also be useful for things like kd-trees which have no corresponding `elm-geometry` implementation currently.

I'm also happy to try to answer questions on the `elm-geometry` implementations of polygon triangulation, Delaunay triangulation etc., if that's helpful.

**Comment by ianmackenzie** [comment]
(By the way, in case you were curious, the Elm Slack has a **#packages** channel with an automated live feed of newly published packages, which I assume is also how @MartinSStewart found out about this package so fast...)

**Comment by MartinSStewart** [comment]
Indeed. That channel is incredibly useful.
